default: styles/mastodon-bird-ui-dark.scss
mastodon-bird-ui-light: styles/mastodon-bird-ui-light.scss
mastodon-bird-ui-contrast: styles/mastodon-bird-ui-contrast.scss
mastodon-dark: styles/application.scss
mastodon-light: styles/mastodon-light.scss
contrast: styles/contrast.scss
mustard-theme: styles/mustard-theme.scss
